import { Ticket } from './model';

const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();

export const seedTickets: Ticket[] = [
  {
    id: 'SUP-1048',
    customer: 'Maya Chen',
    initials: 'MC',
    country: 'Singapore',
    subject: 'Subscription restored on the wrong profile',
    preview: 'The purchase is active in Apple settings, but the app still shows the free plan.',
    priority: 'urgent',
    status: 'open',
    channel: 'in-app',
    assignee: 'David',
    createdAt: minutesAgo(7),
    slaMinutes: 15,
    tags: ['billing', 'ios'],
    messages: [
      {
        id: 'm-1048-1',
        author: 'customer',
        body: 'I restored my purchase twice. Apple shows the annual plan as active, but I am still on the free plan in the app.',
        createdAt: minutesAgo(7),
      },
      {
        id: 'm-1048-2',
        author: 'system',
        body: 'Purchase receipt detected. Account entitlement sync did not complete.',
        createdAt: minutesAgo(6),
      },
    ],
  },
  {
    id: 'SUP-1047',
    customer: 'Elena Rossi',
    initials: 'ER',
    country: 'Italy',
    subject: 'Outfit analysis stops near completion',
    preview: 'The progress reaches 92%, then returns me to the upload screen.',
    priority: 'high',
    status: 'open',
    channel: 'in-app',
    assignee: 'Nina',
    createdAt: minutesAgo(19),
    slaMinutes: 45,
    tags: ['generation', 'android'],
    messages: [
      {
        id: 'm-1047-1',
        author: 'customer',
        body: 'My first photo worked yesterday. Today the progress reaches 92% and the app takes me back to upload.',
        createdAt: minutesAgo(19),
      },
      {
        id: 'm-1047-2',
        author: 'agent',
        body: 'Thanks for the detail. I am checking the generation status and your attempt balance now.',
        createdAt: minutesAgo(15),
      },
    ],
  },
  {
    id: 'SUP-1046',
    customer: 'Noah Williams',
    initials: 'NW',
    country: 'Canada',
    subject: 'How can I change my style profile?',
    preview: 'I want to update the colors and occasions I selected during onboarding.',
    priority: 'normal',
    status: 'pending',
    channel: 'email',
    assignee: 'David',
    createdAt: minutesAgo(64),
    slaMinutes: 240,
    tags: ['profile', 'how-to'],
    messages: [
      {
        id: 'm-1046-1',
        author: 'customer',
        body: 'Where can I update the colors and occasions I selected when I first joined?',
        createdAt: minutesAgo(64),
      },
      {
        id: 'm-1046-2',
        author: 'agent',
        body: 'Open Profile, choose Style preferences, and select Edit. Your new choices apply to the next analysis.',
        createdAt: minutesAgo(58),
      },
    ],
  },
  {
    id: 'SUP-1045',
    customer: 'Sara Haddad',
    initials: 'SH',
    country: 'United Arab Emirates',
    subject: 'Deleted wardrobe item came back',
    preview: 'One item reappeared after I signed in on my second phone.',
    priority: 'high',
    status: 'open',
    channel: 'in-app',
    assignee: 'Nina',
    createdAt: minutesAgo(82),
    slaMinutes: 90,
    tags: ['wardrobe', 'sync'],
    messages: [
      {
        id: 'm-1045-1',
        author: 'customer',
        body: 'I removed a jacket from my wardrobe, but it returned after I opened the app on another phone.',
        createdAt: minutesAgo(82),
      },
    ],
  },
  {
    id: 'SUP-1044',
    customer: 'Amelia Brown',
    initials: 'AB',
    country: 'United Kingdom',
    subject: 'Refund received, thank you',
    preview: 'Everything is resolved now. Thank you for following up quickly.',
    priority: 'normal',
    status: 'resolved',
    channel: 'email',
    assignee: 'David',
    createdAt: minutesAgo(310),
    slaMinutes: 240,
    tags: ['billing'],
    messages: [
      {
        id: 'm-1044-1',
        author: 'customer',
        body: 'The refund arrived today. Everything is resolved now, thank you for following up.',
        createdAt: minutesAgo(310),
      },
      {
        id: 'm-1044-2',
        author: 'agent',
        body: 'Glad to hear it is resolved. I will close this conversation, and you can reply here if anything changes.',
        createdAt: minutesAgo(300),
      },
    ],
  },
];
